=== dbsystel/cdk-sops-secrets/lambda/internal/event/config-schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema#",
  "$id": "SopsSyncResourceProperties",
  "$defs": {
    "SopsInline": {
      "properties": {
        "Content": {
          "type": "string"
        },
        "Hash": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": ["Content", "Hash"]
    },
    "SopsS3File": {
      "properties": {
        "Bucket": {
          "type": "string"
        },
        "Key": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": ["Bucket", "Key"]
    }
  },
  "properties": {
    "ResourceType": {
      "type": "string",
      "enum": [
        "SECRET",
        "SECRET_RAW",
        "SECRET_BINARY",
        "PARAMETER_MULTI",
        "PARAMETER"
      ]
    },
    "Format": {
      "type": "string",
      "enum": ["json", "yaml", "dotenv", "binary"]
    },
    "Target": {
      "type": "string"
    },
    "EncryptionKey": {
      "type": "string"
    },
    "SopsS3File": {
      "$ref": "#/$defs/SopsS3File"
    },
    "SopsInline": {
      "$ref": "#/$defs/SopsInline"
    },
    "FlattenSeparator": {
      "type": "string"
    },
    "SyncTrigger": {
      "type": "string"
    },
    "ServiceToken": {
      "type": "string"
    }
  },
  "additionalProperties": false,
  "type": "object",
  "required": ["ResourceType", "Format", "Target"]
}

=== dbsystel/cdk-sops-secrets/lambda/events/31-PARAMETER-json.json
{
  "EncryptionKey": "arn:aws:kms:eu-central-1:505755377845:key/58b75958-883a-440c-842c-85af5d33a5bb",
  "Format": "json",
  "ResourceType": "PARAMETER",
  "SopsS3File": {
    "Bucket": "cdk-hnb659fds-assets-505755377845-eu-central-1",
    "Key": "test-secrets/testsecret.sops.json"
  },
  "Target": "/31-PARAMETER-json"
}

=== dbsystel/cdk-sops-secrets/lambda/events/24-SECRET_BINARY-binary.json
{
  "EncryptionKey": "arn:aws:kms:eu-central-1:505755377845:key/58b75958-883a-440c-842c-85af5d33a5bb",
  "Format": "binary",
  "ResourceType": "SECRET_BINARY",
  "SopsS3File": {
    "Bucket": "cdk-hnb659fds-assets-505755377845-eu-central-1",
    "Key": "test-secrets/README.gz.sops.binary"
  },
  "Target": "24-SECRET_BINARY-binary"
}

=== dbsystel/cdk-sops-secrets/lambda/events/21-secret-json-json-true-true.json
{
  "EncryptionKey": "arn:aws:kms:eu-central-1:505755377845:key/58b75958-883a-440c-842c-85af5d33a5bb",
  "Format": "json",
  "Target": "21-secret-json-json-true-true",
  "ResourceType": "SECRET",
  "SopsS3File": {
    "Bucket": "cdk-hnb659fds-assets-505755377845-eu-central-1",
    "Key": "test-secrets/json/sopsfile-complex.enc-age.json"
  }
}

=== dbsystel/cdk-sops-secrets/lambda/events/25-secret-dotenv-json-true-true.json
{
  "EncryptionKey": "arn:aws:kms:eu-central-1:505755377845:key/58b75958-883a-440c-842c-85af5d33a5bb",
  "FlattenSeparator": ".",
  "Format": "dotenv",
  "Target": "25-secret-dotenv-json-true-true",
  "ResourceType": "SECRET",
  "SopsS3File": {
    "Bucket": "cdk-hnb659fds-assets-505755377845-eu-central-1",
    "Key": "test-secrets/dotenv/encrypted-best-secret.env"
  }
}

=== dbsystel/cdk-sops-secrets/lambda/events/02-secret-binary-binary-true-true.json
{
    "EncryptionKey": "arn:aws:kms:eu-central-1:505755377845:key/58b75958-883a-440c-842c-85af5d33a5bb",
    "Format": "binary",
    "Target": "02-secret-binary-binary-true-true",
    "ResourceType": "SECRET_BINARY",
    "SopsS3File": {
      "Bucket": "cdk-hnb659fds-assets-505755377845-eu-central-1",
      "Key": "test-secrets/binary/sopsfile.enc-age.binary"
    }
  }

=== dbsystel/cdk-sops-secrets/lambda/events/01-parameter-binary-binary-true-true.json
{
    "EncryptionKey": "arn:aws:kms:eu-central-1:505755377845:key/58b75958-883a-440c-842c-85af5d33a5bb",
    "Format": "binary",
    "Target": "01-parameter-binary-binary-true-true",
    "ResourceType": "PARAMETER",
    "SopsS3File": {
      "Bucket": "cdk-hnb659fds-assets-505755377845-eu-central-1",
      "Key": "test-secrets/binary/sopsfile.enc-age.binary"
    },
    "ServiceToken": "arn:aws:lambda:eu-central-1:505755377845:function:SecretsManagerResourceHandler"
  }
